version: "3.8"
services:
  app:
    build:
      context: https://github.com/joseaplicativosapge-maker/erp-bachestic.git
    ports:
      - "3005:3000"
    environment:
      - NODE_ENV=production
      - GEMINI_API_KEY=tu_key_real_aqui
      - DATABASE_URL=/data/bachestic.db
    volumes:
      - sqlite_data:/data
    restart: unless-stopped

volumes:
  sqlite_data: